version: "3"

services:
  app:
    build:
      context: ./app/
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./app/src/
        target: /home/local/
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 9005:9005 # for firebase login
    networks:
      - websocket
    depends_on:
      - server
    command: >
      sh -c "npm run dev"

  server:
    build:
      context: ./server/
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./server/src/
        target: /home/local/
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    networks:
      - websocket
    command: >
      sh -c "go run main.go"

networks:
  websocket:
    driver: bridge
